name: Linux Build Artifact
concurrency:
  group: linux_build_artifact_${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.rst"
      - "docs/**"
  push:
    paths-ignore:
      - "**.rst"
      - "docs/**"

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_REPO_JAVET: ${{ secrets.DOCKERHUB_REPO_JAVET }}
  JAVET_VERSION: 2.0.2

jobs:
  javet_linux_x86_64:
    name: Build Javet Linux x86_64 Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Build the Artifact
        run: |
          export BASE_GRADLE_IMAGE_TAG=${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO_JAVET }}:x86_64-${{ env.JAVET_VERSION }}
          docker build -t javet:local \
            --build-arg BASE_GRADLE_IMAGE_TAG=${BASE_GRADLE_IMAGE_TAG} \
            -f docker/linux-x86_64/build_artifact.Dockerfile .

      - name: Copy the Artifact
        run: mkdir $PWD/build && docker run --rm -i -v $PWD/build:/output javet:local cp -rf /Javet/build/libs /output

      - name: Upload the Artifact
        uses: actions/upload-artifact@v3
        with:
          name: javet-linux-x86_64
          path: build/libs/javet*.jar
