name: Linux Build (2/2) Artifact
concurrency:
  group: linux_build_artifact_${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.rst"
      - "docs/**"
  push:
    paths-ignore:
      - "**.rst"
      - "docs/**"

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_REPO_JAVET: ${{ secrets.DOCKERHUB_REPO_JAVET }}
  JAVET_NODE_VERSION: 20.10.0
  JAVET_V8_VERSION: 12.1.285.19
  JAVET_VERSION: 3.0.3

jobs:
  javet_linux_x86_64:
    name: Build Javet Linux x86_64 Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Build the Artifact
        run: |
          docker build -t javet:local \
            --build-arg JAVET_REPO=${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO_JAVET }} \
            --build-arg JAVET_NODE_VERSION=${{ env.JAVET_NODE_VERSION }} \
            --build-arg JAVET_V8_VERSION=${{ env.JAVET_V8_VERSION }} \
            --build-arg JAVET_VERSION=${{ env.JAVET_VERSION }} \
            -f docker/linux-x86_64/build_artifact.Dockerfile .

      - name: Copy the Artifact
        run: mkdir $PWD/build && docker run --rm -i -v $PWD/build:/output javet:local cp -rf /Javet/build/libs /output

      - name: Upload the Artifact
        uses: actions/upload-artifact@v3
        with:
          name: javet-linux-x86_64
          path: build/libs/javet*.jar
